### ISSUE TITLE
fail to build linphone-sdk on raspberry pi 4 

### ISSUE THREAD

**Issue by pascalcarreweyn** [BelledonneCommunications/linphone-sdk#14]
i have a raspberry pi 4 , fully installed and brand new.

i do the next steps 
-------------------
1) git clone https://gitlab.linphone.org/BC/public/linphone-sdk --recursive
2) installed doxygem , yasm,  pystache and six 
3) cd linphone-sdk
3) mkdir build
4) cd build
5) cmake LINPHONESDK_PLATFORM=Raspberry ..
6) cmake --build .

   here it goes wrong if it tries to build an external application, in the attachment you find the full error messages, here under is just a part
---------------------------------------------------------------------

 /home/pi/linphone-sdk/external/opus/celt/arm/celt_neon_intr.c: In function ‘xcorr_kernel_neon_float’:
/usr/lib/gcc/arm-linux-gnueabihf/8/include/arm_neon.h:6740:1: error: inlining failed in call to always_inline ‘vdupq_n_f32’: target specific option mismatch

make[8]: *** [CMakeFiles/opus.dir/build.make:1857: CMakeFiles/opus.dir/celt/arm/celt_neon_intr.c.o] Fout 1
..
make[7]: *** [CMakeFiles/Makefile2:73: CMakeFiles/opus.dir/all] Fout 2
make[6]: *** [Makefile:130: all] Fout 2
make[5]: *** [CMakeFiles/EP_opus.dir/build.make:113: /home/pi/linphone-sdk/build/WORK/desktop/Stamp/EP_opus/EP_opus-build] Fout 2
make[4]: *** [CMakeFiles/Makefile2:1093: CMakeFiles/EP_opus.dir/all] Fout 2
make[3]: *** [Makefile:84: all] Fout 2
make[2]: *** [CMakeFiles/sdk.dir/build.make:113: sdk-prefix/src/sdk-stamp/sdk-build] Fout 2
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/sdk.dir/all] Fout 2
make: *** [Makefile:84: all] Fout 2

---------------------------------------------------------

i don't think i need this.
The only thing i need is to install the liblinphone.

I already have been trying for several days.
Can you help me out ?

Thanks in advance.
Pascal

[foutboodschapbij buildlinphone.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/4405103/foutboodschapbij.buildlinphone.txt)

**Comment by amxyz-cyber** [comment]
You're getting this error, because the OPUS-Option still can't be compiled on the raspi. 

I could install it as an aarch64 binary on the raspi 4 using the following commands:

$ pip install pystache --user
$ git clone https://gitlab.linphone.org/BC/public/linphone-desktop.git --recursive
$ cd linphone-desktop
$ mkdir build
$ cd build
$ cmake  --prefix=/usr/local/ .. -DCMAKE_BUILD_TYPE=aarch64-unknown-linux-gnu -DENABLE_MKV=NO -DENABLE_OPUS=NO -DENABLE_VPX=NO -DENABLE_WEBRTC_AEC=NO -DENABLE_FFMPEG=ON -DENABLE_V4L=NO -DENABLE_OPENH264=ON -DENABLE_NON_FREE_CODECS=ON -DENABLE_JPEG=NO -DENABLE_ZLIB=NO  -D CMAKE_CXX_FLAGS="-fPIC" 
--> maybe you can skip the -fPIC-Option
$ make
# cmake --install .
--> The binaries will be placed in:
~/linphone-desktop/build/OUTPUT/bin/

The installation process is really annoying. It took me a while and also after starting the app the buttons seem to have strange names such as "inviteButton", etc. They really understand something about the usability theory, don't they?!
