### ISSUE TITLE
LinphoneSDK used on macOS

### ISSUE THREAD

**Issue by JWXIAN** [BelledonneCommunications/linphone-sdk#19]
lc = linphone_core_new_with_config(&vtable, NULL, NULL);

Linphonesdk used on Macos, can not continue to compile, prompt Thread 1: EXC_BAD_ACCESS (code=1, address=0x8)

**Comment by KyronNextLevel** [comment]
Hello.
This seems caused by an unavailable pointer.
Can you please give a bit of context? (what do you want to do with the SDK? what are you expecting?)
You can try debugging it by using XCode zombies [https://code.tutsplus.com/tutorials/what-is-exc_bad_access-and-how-to-debug-it--cms-24544](https://code.tutsplus.com/tutorials/what-is-exc_bad_access-and-how-to-debug-it--cms-24544)
I can't help you more without more details.

**Comment by Peter-iOS** [comment]
Hi,bro.How did you solve this problem later?
