### ISSUE TITLE
error for installing the linphone sdk for OS X version using CocoPods

### ISSUE THREAD

**Issue by siavashnamiranian** [BelledonneCommunications/linphone-sdk#207]
![image](https://user-images.githubusercontent.com/68529832/150696449-6c0f070c-b3d0-4375-80ab-fdf3274c7061.png)

I tried to install the linphone sdk for OS X version using CocoPods
I added the following command in the podfile.
pod 'linphone-sdk', :source => 'https://gitlab.linphone.org/BC/public/podspec-macos.git'

and hit the pod install command in terminal, which caused the following error:
[!] Couldn't determine repo type for URL: `https://gitlab.linphone.org/BC/public/podspec-macos.git`: (<unknown>): mapping values are not allowed in this context at line 3 column 17

Xcode:  13.1
OS: mac os 11.6 
Cpu: M1

**Comment by KyronNextLevel** [comment]
Hello.
I have fixed it.

This was caused by the fact that Gitlab attempts to redirect to a login page with a 302 when a file isn't found, making Cocoapods fail.
It took us some time to figure it out, because the error really isn't helpful.

The workaround was [to follow this part of the Gitlab documentation related to NGINX configuration](https://docs.gitlab.com/omnibus/settings/nginx.html#inserting-custom-nginx-settings-into-the-gitlab-server-block) to forbid the direct download of Cocoapods-version.yml (we only provides the podspec anyway)

Please clean your cache 
`pod cache clean linphone-sdk`

And launch the install again
`pod install --verbose`

Do not hesitate to tell me if you experience the issue again.
