### ISSUE TITLE
Tapping/Clicking noise in conference

### ISSUE THREAD

**Issue by zeejaydev** [BelledonneCommunications/linphone-sdk#329]
Hello guys!

1. **Describe the bug** (mandatory)

When i start a new conference call and after connecting all parties, once I start talking (or any noise my phone mic picks up) the connected calls start hearing a ticking/tapping noise loud and continuous, I don't hear anything on my side, but it makes it impossible and very annoying for other people to communicate with me and each other.

Also when I hit the icon to  start conference the view switch back to active call view and on the bottom I get a toast saying "All other participants have left the group call"
I have to go back to call list and hit the conference icon again. 

I am on Linphone Android 5.0.14
Linphone SDK 5.2.77

**If the issue is about the SDK (build, issue, etc...) open the ticket in the [linphone-sdk](https://github.com/BelledonneCommunications/linphone-sdk) repository or one of it's submodules!**

2. **To Reproduce** (mandatory)

Start a new conference then start talking

3. **Expected behavior** (mandatory)

No continuous tapping or clicking noise while speaking

4. **Please complete the following information** (mandatory)

 - Device: Samsung S22 Ultra
 - OS: Android 12
 - Version of the App 5.0.14
 - Version of the SDK 5.2.77
 - installed from Google Play Store

5. **SDK logs** (mandatory)

logs attached

[64c928ada9688_36ab89343c1c1cb6901e.gz](https://github.com/BelledonneCommunications/linphone-android/files/12231685/64c928ada9688_36ab89343c1c1cb6901e.gz)

**Comment by zeejaydev** [comment]
Any update on this please??

**Comment by smorlat** [comment]
Hi,

During conferences when acting as the conference mixing endpoint, linphone/liblinphone 5.2 sends volume information in RTP packets every 500 ms, so that it becomes possible to visually show who is speaking at any time on other linphone clients.
These audio volume information are sent as RTP extension header following this specification: https://datatracker.ietf.org/doc/html/rfc6465

This problem happens because the SIP server in the middle decodes the audio but does not ignore the extension header as it should do per RFC3550. This volume information consisting in a few bytes is then retransmitted as part of the audio, which generates these periodic ticking noise for other clients.

The fix is to be done in the SIP server code.

A workaround consists in disabling the transmission of RTP volumes in liblinphone, which of course cause the is-speaking visualization to be non-working.
This can be done by setting the following properties in linphonerc factory configuration file:

[rtp]
use_volumes=0

Best regards,

Simon

**Comment by zeejaydev** [comment]
I see, thanks for explaining that, I had to use linphone-sdk 5.0 as a work around.

**Comment by happyfsyy** [comment]
> Hi,
> 
> During conferences when acting as the conference mixing endpoint, linphone/liblinphone 5.2 sends volume information in RTP packets every 500 ms, so that it becomes possible to visually show who is speaking at any time on other linphone clients. These audio volume information are sent as RTP extension header following this specification: https://datatracker.ietf.org/doc/html/rfc6465
> 
> This problem happens because the SIP server in the middle decodes the audio but does not ignore the extension header as it should do per RFC3550. This volume information consisting in a few bytes is then retransmitted as part of the audio, which generates these periodic ticking noise for other clients.
> 
> The fix is to be done in the SIP server code.
> 
> A workaround consists in disabling the transmission of RTP volumes in liblinphone, which of course cause the is-speaking visualization to be non-working. This can be done by setting the following properties in linphonerc factory configuration file:
> 
> [rtp] use_volumes=0
> 
> Best regards,
> 
> Simon

Hello, @smorlat @zeejaydev 
I just found that my problem is very similar to this. 
I tried your method, the specific code is as follows, but it didn't work.

``` kotlin
val config=Factory.instance().createConfigWithFactory(corePreferences.configPath, corePreferences.factoryPath)
config.setString("rtp","use_volumes","0")
corePreferences.config=config
```
Is there a problem with my code? How should I write?
Thanks in advance.

**Comment by zeejaydev** [comment]
@happyfsyy I think it needs to be set on core when the app first launch, like 
`core.config.setBool(section: "rtp", key: "use_volumes", value: false)`

**Comment by happyfsyy** [comment]
@zeejaydev Hello, I have solved this problem.
My previous code didn't work because I didn't update the sdk to a version later than 5.3.
Thank you very much for your reply.
