### ISSUE TITLE
REGISTER: Content-Length header field value MUST be set to zero.

### ISSUE THREAD

**Issue by sergey-safarov** [BelledonneCommunications/linphone-sdk#50]
I found that Kamailio sanity-check block REGISTER messages from Linphone with message
```
sanity [sanity.c:585]: check_cl(): content length header missing in request
```
According [rfc3261#section-20.14](https://tools.ietf.org/html/rfc3261#section-20.14)
> If no body is present in a message, then the
   Content-Length header field value MUST be set to zero.

And
> If a stream-based protocol (such as TCP) is used as
   transport, the header field MUST be used.

Could you add `Content-Length` for all messages?

**Comment by smorlat** [comment]
Hi,

Linphone always adds Content-length for message sent over a stream-based transport (TCP & TLS), according to RFC3261.
The Content-length is absolutely not mandatory over fragment-based transports such as UDP or DTLS.
Please see https://tools.ietf.org/html/rfc3261#section-18.3

18.3 Framing

   In the case of message-oriented transports (such as UDP), if the
   message has a Content-Length header field, the message body is
   assumed to contain that many bytes.  If there are additional bytes in
   the transport packet beyond the end of the body, they MUST be
   discarded.  If the transport packet ends before the end of the
   message body, this is considered an error.  If the message is a
   response, it MUST be discarded.  If the message is a request, the
   element SHOULD generate a 400 (Bad Request) response.  If the message
   has no Content-Length header field, the message body is assumed to
   end at the end of the transport packet.

   In the case of stream-oriented transports such as TCP, the Content-
   Length header field indicates the size of the body.  The Content-
   Length header field MUST be used with stream oriented transports.

--

The sentence "If no body is present in a message, then the
Content-Length header field value MUST be set to zero." means that if Content-Length header is present and no body is present, the content-length value must be zero.
It doesn't mean that a Content-length header must be present in all cases.

Please make sure that kamailio rejects the message in the case of UDP. If yes, it is a bug. If received over TCP or TLS, it means that the message is not coming directly from Linphone. A proxy in the middle could have changed the transport without adding the Content-length. The bug is then in the proxy in the middle.

Best regards,

Simon
