### ISSUE TITLE
Related to sal media description #69

### ISSUE THREAD

**Issue by gregperezz** [BelledonneCommunications/linphone-sdk#74]
Hi @Viish, related to the sal media description BelledonneCommunications/linphone-sdk#69 issue, I tried the same scenario from scratch today and saved the linphone logs. I attached them to this issue. There are two calls in the log. First one has one way audio (linphone does not hear), the second call is successful, both end points can hear each other. The configuration is totally the same, the sip service provider, phones (both model and configuration, codecs, media etc.), linphone app version. The sip messages also look like the same but you can see that at the end of the first call, "Audio Session's RTP Statistics" logs shows that even though many bytes are received there is no audio. Either I am missing something or there is a problem at the Linphone side.

[linphone_logs.txt](https://github.com/BelledonneCommunications/linphone-android/files/5465069/linphone_logs.txt)

**Comment by gregperezz** [comment]
Hi, @Viish could you analyze the error?

**Comment by Viish** [comment]
Problem is your second call shouldn't have audio has the 200 OK disables the audio mline.
@smorlat Do you have an idea?

**Comment by gregperezz** [comment]
The second call is successful with two way audio. The first call has one way audio. What is mline?

**Comment by gregperezz** [comment]
The second call is successful with two way audio. The first call has one way audio. What is mline @Viish ?

**Comment by gregperezz** [comment]
@Viish I guess you mean m=audio lines. 
Both calls have both "m=audio 7078 RTP/SAVP .." and "m=audio 0 RTP/AVP .." lines in their 200 OK's.

**Comment by Viish** [comment]
Indeed I didn't noticed the fist audio mline.
Then I don't know why it works for one and not the other.

**Comment by gregperezz** [comment]
@Viish Calls were made one after the other. It is really strange. I made 6 calls in total 3 of them were successful, the other three had one way audio (it doesn't happen in an ordered way). @smorlat can you help with this problem?

**Comment by smorlat** [comment]
Hi,

In the failed call, Linphone doesn't receive a single audio RTP packet.
There is no error and no anomaly from a SIP and SDP standpoint.
It looks like a server issue.
Since the SIP flow is transmitted over UDP, we can't exclude that some buggy SIP-aware NAT device is doing bad things.
I would advice to switch to TLS first if server supports it.
Otherwise the issue has to be investigated server side. Start with a wireshark capture on the server to check where it sends the RTP packets if any. If it doesn't send RTP packets, then check the server logs: there is surely an indication of what went wrong.

Best regards,

Simon

**Comment by gregperezz** [comment]
Thank you @smorlat. We have found the issue.

Best regards.
